Dynamic workflow

diff --git a/.github/workflows/07akioni-xicons-use-template-generated.yml b/.github/workflows/07akioni-xicons-use-template-generated.yml
--- a/.github/workflows/07akioni-xicons-use-template-generated.yml
+++ b/.github/workflows/07akioni-xicons-use-template-generated.yml
@@ -105,13 +105,17 @@ jobs:
       working-directory: ${{ env.package_json_path }}
     - name: Build
       run: |
-        if [ -f package-lock.json ]; then
-          npm run build --if-present
-        elif [ -f pnpm-lock.yaml ]; then
-          pnpm run build --if-present
+        if [ -f "package.json" ] && [ "$(node -e "const pkg = require('./package.json'); console.log(pkg.scripts && pkg.scripts.build ? 'true' : 'false');")" = "true" ]; then
+          if [ -f "package-lock.json" ]; then
+            npm run build
+          elif [ -f "pnpm-lock.yaml" ]; then
+            pnpm run build
+          else
+            echo "Lock file not found. Cannot run build scripts."
+            exit 1
+          fi
         else
-          echo "Lock file not found. Cannot run build scripts."
-          exit 1
+          echo "No build script found in package.json"
         fi
       working-directory: ${{ env.package_json_path }}
     - name: Apply patch
