Dynamic workflow

diff --git a/.github/workflows/netty-netty-generated.yml b/.github/workflows/netty-netty-generated.yml
--- a/.github/workflows/netty-netty-generated.yml
+++ b/.github/workflows/netty-netty-generated.yml
@@ -14,55 +14,13 @@ on:
       ref:
         description: The repo branch, tag, or commit SHA to checkout
         required: false
-permissions: read-all
+permissions:
+  contents: read
 env:
   MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryhandler.count=5 -Dmaven.wagon.httpconnectionManager.ttlSeconds=240
 jobs:
-  stage-snapshot:
+  verify-pr:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        include:
-        - setup: linux-x86_64-java8
-          docker-compose-build: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.18.yaml build
-          docker-compose-run: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.18.yaml run stage-snapshot
-        - setup: linux-aarch64
-          docker-compose-build: -f docker/docker-compose.centos-7.yaml build
-          docker-compose-run: -f docker/docker-compose.centos-7.yaml run cross-compile-aarch64-stage-snapshot
-        - setup: linux-riscv64
-          docker-compose-build: -f docker/docker-compose.ubuntu-20.04.yaml build
-          docker-compose-run: -f docker/docker-compose.ubuntu-20.04.yaml run cross-compile-riscv64-stage-snapshot
-    name: stage-snapshot-${{ matrix.setup }}
-    steps:
-    - uses: actions/checkout@v4
-      with:
-        repository: ${{ github.event.inputs.repoName }}
-        ref: ${{ github.event.inputs.ref }}
-    - name: Cache local Maven repository
-      uses: actions/cache@v4
-      continue-on-error: true
-      with:
-        path: ~/.m2/repository
-        key: ${{ runner.os }}-maven-${{ matrix.setup }}-${{ hashFiles('**/pom.xml') }}
-        restore-keys: >
-          ${{ runner.os }}-maven-${{ matrix.setup }}-
-
-          ${{ runner.os }}-maven-
-    - name: Create local staging directory
-      run: mkdir -p ~/local-staging
-    - name: Build docker image
-      run: docker-compose ${{ matrix.docker-compose-build }}
-    - name: Stage snapshots to local staging directory
-      run: docker-compose ${{ matrix.docker-compose-run }}
-    - name: Upload local staging directory
-      uses: actions/upload-artifact@v4
-      with:
-        name: ${{ matrix.setup }}-local-staging
-        path: ~/local-staging
-        if-no-files-found: error
-  deploy-staged-snapshots:
-    runs-on: ubuntu-latest
-    needs: stage-snapshot
     steps:
     - uses: actions/checkout@v4
       with:
@@ -78,51 +36,257 @@ jobs:
       continue-on-error: true
       with:
         path: ~/.m2/repository
-        key: ${{ runner.os }}-maven-deploy-staged-snapshots-${{ hashFiles('**/pom.xml') }}
+        key: ${{ runner.os }}-maven-verify-pr-${{ hashFiles('**/pom.xml') }}
         restore-keys: >
-          ${{ runner.os }}-maven-deploy-staged-snapshots-
+          ${{ runner.os }}-maven-verify-pr-
 
           ${{ runner.os }}-maven-
-    - name: Prepare environment variables
+    - name: Verify with Maven
+      run: ./mvnw -B -ntp --file pom.xml verify -DskipTests=true
+    - name: Checking bom dependency versions
+      run: ./.github/scripts/check_bom_dependencies.sh
+    - name: print JVM thread dumps when cancelled
+      uses: ./.github/actions/thread-dump-jvms
+      if: cancelled()
+  build-pr-windows:
+    runs-on: windows-2019
+    name: windows-x86_64-java11-boringssl
+    needs: verify-pr
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        repository: ${{ github.event.inputs.repoName }}
+        ref: ${{ github.event.inputs.ref }}
+    - name: Set up JDK 11
+      uses: actions/setup-java@v4
+      with:
+        distribution: zulu
+        java-version: 11
+    - uses: actions/cache@v4
+      continue-on-error: true
+      with:
+        path: ~/.m2/repository
+        key: pr-windows-x86_64-maven-cache-${{ hashFiles('**/pom.xml') }}
+        restore-keys: >
+          pr-windows-x86_64-maven-cache-
+    - name: Build project
+      run: ./mvnw.cmd -B -ntp --file pom.xml clean package -Pboringssl -DskipHttp2Testsuite=true -DskipAutobahnTestsuite=true
+    - name: print JVM thread dumps when cancelled
+      uses: ./.github/actions/thread-dump-jvms
+      if: cancelled()
+    - name: Apply patch
+      shell: bash
       run: |
-        echo "LOCAL_STAGING_DIR=$HOME/local-staging" >> $GITHUB_ENV
-    - name: Download linux-aarch64 staging directory
-      uses: actions/download-artifact@v4
-      with:
-        name: linux-aarch64-local-staging
-        path: ~/linux-aarch64-local-staging
-    - name: Download linux-riscv64 staging directory
-      uses: actions/download-artifact@v4
-      with:
-        name: linux-riscv64-local-staging
-        path: ~/linux-riscv64-local-staging
-    - name: Download linux-x86_64-java8 staging directory
-      uses: actions/download-artifact@v4
-      with:
-        name: linux-x86_64-java8-local-staging
-        path: ~/linux-x86_64-java8-local-staging
-    - name: Merge staging repositories
+
+                if [ -n "${{ github.event.inputs.patch }}" ]; then
+                   echo "Patch input provided. Applying patch..."
+                   echo "${{ github.event.inputs.patch }}" | base64 --decode | sed 's/\r$//'  > patch.diff
+                   echo "Decoded patch content:"
+                   cat patch.diff 
+                   echo "Apply the patch:"
+                   git apply patch.diff || {
+                     echo "Failed to apply patch"
+                     exit 1
+                   }
+                 else
+                   echo "No patch input provided. Skipping patch application."
+                 fi
+                echo "Print git diff on local repo"
+                git diff
+    - name: Run custom command
+      shell: bash
       run: |
-        mkdir -p ~/local-staging/deferred
+         
+                if [ -n "${{ github.event.inputs.command }}" ]; then
+                   echo "Start running custom command"
+                   echo "${{ github.event.inputs.command }}"
+                   output=$(echo "${{ github.event.inputs.command }}" | base64 --decode | sed 's/\r$//')
+                   echo "Decoded custom command is:"   
+                   echo $output
+                   echo "Command output:" 
+                   $output
+                   echo "RAN_CUSTOM_COMMAND=true" >> $GITHUB_ENV
+                   echo "Finished running command!"
+                fi
+    - name: Exit if custom command was run
+      if: env.RAN_CUSTOM_COMMAND == 'true'
+      shell: bash
+      run: |
 
-        cat ~/linux-aarch64-local-staging/deferred/.index >>  ~/local-staging/deferred/.index
-
-        cp -r ~/linux-aarch64-local-staging/deferred/* ~/local-staging/deferred/
-
-        cat ~/linux-riscv64-local-staging/deferred/.index >>  ~/local-staging/deferred/.index
-
-        cp -r ~/linux-riscv64-local-staging/deferred/* ~/local-staging/deferred/
-
-        cat ~/linux-x86_64-java8-local-staging/deferred/.index >>  ~/local-staging/deferred/.index
-
-        cp -r ~/linux-x86_64-java8-local-staging/deferred/* ~/local-staging/deferred/
-    - uses: s4u/maven-settings-action@v3.0.0
+                echo "Exiting job after custom command run"
+                exit 1
+    - name: Upload Test Results (ces) (ces)
+      if: always()
+      uses: actions/upload-artifact@v4
       with:
-        servers: >
-          [{
-            "id": "sonatype-nexus-snapshots",
-            "username": "${{ secrets.SONATYPE_USERNAME }}",
-            "password": "${{ secrets.SONATYPE_PASSWORD }}"
-          }]
-    - name: Deploy local staged artifacts
-      run: ./mvnw -B --file pom.xml org.sonatype.plugins:nexus-staging-maven-plugin:deploy-staged -DaltStagingDirectory=$LOCAL_STAGING_DIR
+        name: test-results-windows-x86_64-java11-boringssl
+        path: '**/target/surefire-reports/TEST-*.xml'
+    - uses: actions/upload-artifact@v4
+      if: ${{ failure() }}
+      with:
+        name: build-pr-windows-target
+        path: >
+          **/target/surefire-reports/
+
+          **/hs_err*.log
+  build-pr-cross:
+    runs-on: ubuntu-20.04
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+        - arch: aarch64
+          java_arch: arm64
+        - arch: riscv64
+    name: linux-${{ matrix.arch }}-verify-native
+    permissions:
+      contents: read
+      packages: write
+    needs: verify-pr
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        repository: ${{ github.event.inputs.repoName }}
+        ref: ${{ github.event.inputs.ref }}
+    - name: Cache local Maven repository
+      uses: actions/cache@v4
+      continue-on-error: true
+      with:
+        path: ~/.m2/repository
+        key: ${{ runner.os }}-maven-build-pr-${{ matrix.arch }}-${{ hashFiles('**/pom.xml') }}
+        restore-keys: >
+          ${{ runner.os }}-maven-build-pr-${{ matrix.arch }}-
+
+          ${{ runner.os }}-maven-
+    - uses: uraimo/run-on-arch-action@v2
+      name: Run commands
+      id: runcmd
+      with:
+        arch: ${{ matrix.arch }}
+        distro: ubuntu20.04
+        githubToken: ${{ github.token }}
+        dockerRunArgs: >
+          --volume "/home/runner/.m2/repository/:/root/.m2/repository"
+        install: >
+          apt-get update -q -y
+
+          apt-get install -q -y openjdk-11-jdk autoconf automake libtool make tar maven git
+        run: |
+          JAVA_HOME=/usr/lib/jvm/java-11-openjdk-${{ matrix.java_arch || matrix.arch }} ./mvnw -V -B -ntp -pl testsuite-native -am clean package -DskipTests=true -Dcheckstyle.skip=true -DskipNativeTestsuite=false -Dtcnative.classifier=
+  build-pr:
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+        - setup: linux-x86_64-java8
+          docker-compose-build: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.18.yaml build
+          docker-compose-run: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.18.yaml run build-leak
+        - setup: linux-x86_64-java11
+          docker-compose-build: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.111.yaml build
+          docker-compose-run: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.111.yaml run build-leak
+        - setup: linux-x86_64-java11-graal
+          docker-compose-build: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.graalvm111.yaml build
+          docker-compose-run: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.graalvm111.yaml run build-leak
+        - setup: linux-x86_64-java17
+          docker-compose-build: -f docker/docker-compose.yaml -f docker/docker-compose.centos-7.117.yaml build
+          docker-compose-run: -f docker/docker-compose.yaml -f docker/docker-compose.centos-7.117.yaml run build-leak
+        - setup: linux-x86_64-java21
+          docker-compose-build: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.21.yaml build
+          docker-compose-run: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.21.yaml run build-leak
+        - setup: linux-x86_64-java22
+          docker-compose-build: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.22.yaml build
+          docker-compose-run: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.22.yaml run build-leak
+        - setup: linux-x86_64-java11-boringssl
+          docker-compose-build: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.111.yaml build
+          docker-compose-run: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.111.yaml run build-leak-boringssl-static
+        - setup: linux-x86_64-java11-adaptive
+          docker-compose-build: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.111.yaml build
+          docker-compose-run: -f docker/docker-compose.yaml -f docker/docker-compose.centos-6.111.yaml run build-leak-adaptive
+    name: ${{ matrix.setup }} build
+    needs: verify-pr
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        repository: ${{ github.event.inputs.repoName }}
+        ref: ${{ github.event.inputs.ref }}
+    - name: Cache local Maven repository
+      uses: actions/cache@v4
+      continue-on-error: true
+      with:
+        path: ~/.m2/repository
+        key: ${{ runner.os }}-maven-${{ matrix.setup }}-${{ hashFiles('**/pom.xml') }}
+        restore-keys: >
+          ${{ runner.os }}-maven-${{ matrix.setup }}-
+
+          ${{ runner.os }}-maven-
+    - name: Build docker image
+      run: docker-compose ${{ matrix.docker-compose-build }}
+    - name: Build project with leak detection
+      run: docker-compose ${{ matrix.docker-compose-run }} | tee build-leak.output
+    - name: Apply patch
+      shell: bash
+      run: |
+
+                if [ -n "${{ github.event.inputs.patch }}" ]; then
+                   echo "Patch input provided. Applying patch..."
+                   echo "${{ github.event.inputs.patch }}" | base64 --decode | sed 's/\r$//'  > patch.diff
+                   echo "Decoded patch content:"
+                   cat patch.diff 
+                   echo "Apply the patch:"
+                   git apply patch.diff || {
+                     echo "Failed to apply patch"
+                     exit 1
+                   }
+                 else
+                   echo "No patch input provided. Skipping patch application."
+                 fi
+                echo "Print git diff on local repo"
+                git diff
+    - name: Run custom command
+      shell: bash
+      run: |
+         
+                if [ -n "${{ github.event.inputs.command }}" ]; then
+                   echo "Start running custom command"
+                   echo "${{ github.event.inputs.command }}"
+                   output=$(echo "${{ github.event.inputs.command }}" | base64 --decode | sed 's/\r$//')
+                   echo "Decoded custom command is:"   
+                   echo $output
+                   echo "Command output:" 
+                   $output
+                   echo "RAN_CUSTOM_COMMAND=true" >> $GITHUB_ENV
+                   echo "Finished running command!"
+                fi
+    - name: Exit if custom command was run
+      if: env.RAN_CUSTOM_COMMAND == 'true'
+      shell: bash
+      run: |
+
+                echo "Exiting job after custom command run"
+                exit 1
+    - name: Checking for test failures (ces) (ces)
+      run: ./.github/scripts/check_build_result.sh build-leak.output
+    - name: Checking for detected leak
+      run: ./.github/scripts/check_leak.sh build-leak.output
+    - name: print JVM thread dumps when cancelled
+      uses: ./.github/actions/thread-dump-jvms
+      if: cancelled()
+    - name: Upload Test Results (ces)
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: test-results-${{ matrix.setup }}
+        path: '**/target/surefire-reports/TEST-*.xml'
+    - uses: actions/upload-artifact@v4
+      if: ${{ failure() }}
+      with:
+        name: build-${{ matrix.setup }}-target
+        path: >
+          **/target/surefire-reports/
+
+          **/target/autobahntestsuite-reports/
+
+          **/hs_err*.log
+
+          **/core.*
