Dynamic workflow

diff --git a/.github/workflows/SocketCluster-socketcluster-use-template-generated.yml b/.github/workflows/SocketCluster-socketcluster-use-template-generated.yml
--- a/.github/workflows/SocketCluster-socketcluster-use-template-generated.yml
+++ b/.github/workflows/SocketCluster-socketcluster-use-template-generated.yml
@@ -38,15 +38,30 @@ jobs:
       with:
         node-version: ${{ matrix.node-version }}
         check-latest: true
+    - name: Search for package.json
+      id: search-package-json
+      run: |
+        # Search for package.json file in the repository
+
+        PACKAGE_JSON_PATH=$(find . -name 'package.json' | head -n 1)
+
+        if [ -z "$PACKAGE_JSON_PATH" ]; then
+          echo "No package.json found"
+          exit 1
+        fi
+
+        echo "package_json_path=$(dirname "$PACKAGE_JSON_PATH")" >> $GITHUB_ENV
+      shell: bash
     - name: Check for package-lock.json
       run: |
         if [ ! -f package-lock.json ]; then
           echo "package-lock.json not found, generating..."
           npm install --package-lock-only
         else
-          echo "package-lock.json found, proceeding with install..."
-          npm ci
+          echo "package-lock.json found, checking if in sync with package.json..."
+          npm ls > /dev/null || { echo "package.json and package-lock.json are not in sync. Please run 'npm install' locally and commit the changes."; exit 1; }
         fi
+      working-directory: ${{ env.package_json_path }}
     - name: Install dependencies with npm or pnpm
       run: |
         if [ -f package-lock.json ]; then
@@ -60,6 +75,18 @@ jobs:
           echo "Proceeding with dependency installation..."
           npm ci
         fi
+      working-directory: ${{ env.package_json_path }}
+    - name: Build
+      run: |
+        if [ -f package-lock.json ]; then
+          npm run build --if-present
+        elif [ -f pnpm-lock.yaml ]; then
+          pnpm run build --if-present
+        else
+          echo "Lock file not found. Cannot run build scripts."
+          exit 1
+        fi
+      working-directory: ${{ env.package_json_path }}
     - name: Apply patch
       shell: bash
       run: |
@@ -101,15 +128,22 @@ jobs:
 
                 echo "Exiting job after custom command run"
                 exit 1
-    - name: Build and Test (ces) (ces)
+    - name: Test (ces) (ces)
       run: |
-        if [ -f package-lock.json ]; then
-          npm run build --if-present
-          npm test
-        elif [ -f pnpm-lock.yaml ]; then
-          pnpm run build --if-present
-          pnpm test
+        if [ -f "package.json" ] && [ "$(node -e "const pkg = require('./package.json'); console.log(pkg.scripts && pkg.scripts.test ? true : false);")" = "true" ]; then
+          echo "Test script found in package.json."
+          cat "package.json"
+          if [ -f "package-lock.json" ]; then
+            npm test
+          elif [ -f "pnpm-lock.yaml" ]; then
+            pnpm test
+          else
+            echo "Lock file not found. Cannot run test scripts."
+            exit 1
+          fi
         else
-          echo "Lock file not found. Cannot run build or test scripts."
-          exit 1
+          echo "No test script found in package.json."
+          exit 0
         fi
+      shell: bash
+      working-directory: ${{ env.package_json_path }}
